"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import React from "react";
import MainHero from "../components/MainHero";
import Navbar from "../components/Navbar";
import Layout from "./layout/Layout";

const Home: NextPage = () => {
  console.log("test");
  const { data: session } = useSession();
  const router = useRouter();

  React.useEffect(() => {
    if (router && !session?.user) {
      router.push("/login");
    }
  }, [session, router]);

  return (
    <>
      <Head>
        <title>T3 - myMovie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <MainHero />
        </Layout>
      </main>
    </>
  );
};

export default Home;
