"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import React from "react";
import MainHero from "../components/MainHero";
import Layout from "./layout/Layout";
import MovieRow from "../components/MovieRow";
import requests from "../utils/requests";

const Home: NextPage = () => {
  console.log("test");
  const { data: session } = useSession();
  const router = useRouter();

  React.useEffect(() => {
    if (router && !session?.user) {
      router.push("/login");
    }
  }, [session, router]);

  return (
    <>
      <Head>
        <title>T3 - myMovie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainHero />
        <MovieRow title={"UpComing"} rowID={1} />
      </Layout>
    </>
  );
};

export default Home;
