"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import React from "react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();

  // const { data, isLoading, isError } =
  //   trpc.popularMovies.getPopularMovies.useQuery();
  console.log(session);
  React.useEffect(() => {
    if (router && !session?.user) {
      router.push("/login");
    }
  }, [session, router]);

  // if (isLoading) {
  //   return <div>Loading...</div>;
  // }

  // const {results} = data

  return (
    <>
      <Head>
        <title>T3 - myMovie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
